const ACTION_TYPES = {
  CREATE_TASK_REQUEST:'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS:'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR:'CREATE_TASK_ERROR',

  GET_TASKS_SUCCESS:'CREATE_TASK_SUCCESS',
  GET_TASKS_REQUEST:'CREATE_TASK_REQUEST',
  GET_TASKS_ERROR:'CREATE_TASK_ERROR'
}

export default ACTION_TYPES;